spring.application.name=crudprojects
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mydbwithec2.c9ug0cuaknye.ap-south-1.rds.amazonaws.com:3306/mydb
spring.datasource.username=admin
spring.datasource.password=password123
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>rdslocalmysql setup>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#
#spring.datasource.url=jdbc:mysql://mysqldblocalsetup.c9ug0cuaknye.ap-south-1.rds.amazonaws.com:3306/mydb
#spring.datasource.username=admin
#spring.datasource.password=password123

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>rdssecurity for ec2 setup

#spring.datasource.url=jdbc:mysql://mydbwithec2.c9ug0cuaknye.ap-south-1.rds.amazonaws.com:3306/mydb
#spring.datasource.username=admin
#spring.datasource.password=password123



#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>local db setup

#spring.datasource.url = jdbc:mysql://localhost:3306/just
#spring.datasource.username = root
#spring.datasource.password = RootNewPass456!


